package no.uib.storbioinfogui;

import java.awt.event.KeyEvent;
import no.uib.storbioinfogui.data.Project;
import javax.swing.JOptionPane;

/**
 * A dialog for creating a new Project.
 *
 * @author Harald Barsnes
 */
public class NewProjectDialog extends javax.swing.JDialog {

    private StoreBioinfoGUI storeBioinfoGUI;

    /**
     * Creates a new NewProjectDialog.
     *
     * @param storeBioinfoGUI
     * @param modal
     */
    public NewProjectDialog(StoreBioinfoGUI storeBioinfoGUI, boolean modal) {
        super(storeBioinfoGUI, modal);
        initComponents();

        this.storeBioinfoGUI = storeBioinfoGUI;

        setLocationRelativeTo(storeBioinfoGUI);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectDetailsPanel = new javax.swing.JPanel();
        descriptionJScrollPane = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        contactLabel = new javax.swing.JLabel();
        contactJTextField = new javax.swing.JTextField();
        eMailLabel = new javax.swing.JLabel();
        eMailJTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneJTextField = new javax.swing.JTextField();
        summaryLabel = new javax.swing.JLabel();
        summaryJTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        cancelJButton = new javax.swing.JButton();
        okJButton = new javax.swing.JButton();
        mandatoryLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Project");
        setResizable(false);

        projectDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Project Details"));

        descriptionJTextArea.setColumns(5);
        descriptionJTextArea.setLineWrap(true);
        descriptionJTextArea.setRows(3);
        descriptionJTextArea.setWrapStyleWord(true);
        descriptionJTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptionJTextAreaKeyReleased(evt);
            }
        });
        descriptionJScrollPane.setViewportView(descriptionJTextArea);

        contactLabel.setText("Contact*");

        contactJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contactJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));
        contactJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactJTextFieldKeyReleased(evt);
            }
        });

        eMailLabel.setText("E-mail*");

        eMailJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        eMailJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));
        eMailJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eMailJTextFieldKeyReleased(evt);
            }
        });

        phoneLabel.setText("Phone*");

        phoneJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));
        phoneJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneJTextFieldKeyReleased(evt);
            }
        });

        summaryLabel.setText("Summary*");

        summaryJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        summaryJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));
        summaryJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                summaryJTextFieldKeyReleased(evt);
            }
        });

        descriptionLabel.setText("Description*");

        nameLabel.setText("Name*");

        nameJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));
        nameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameJTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout projectDetailsPanelLayout = new javax.swing.GroupLayout(projectDetailsPanel);
        projectDetailsPanel.setLayout(projectDetailsPanelLayout);
        projectDetailsPanelLayout.setHorizontalGroup(
            projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(projectDetailsPanelLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addGap(28, 28, 28)
                        .addComponent(descriptionJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                    .addGroup(projectDetailsPanelLayout.createSequentialGroup()
                        .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactLabel)
                            .addComponent(eMailLabel)
                            .addComponent(phoneLabel)
                            .addComponent(summaryLabel)
                            .addComponent(nameLabel))
                        .addGap(37, 37, 37)
                        .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameJTextField)
                            .addComponent(eMailJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(summaryJTextField)
                            .addComponent(contactJTextField))))
                .addContainerGap())
        );
        projectDetailsPanelLayout.setVerticalGroup(
            projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMailLabel)
                    .addComponent(eMailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summaryLabel)
                    .addComponent(summaryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(projectDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(projectDetailsPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(descriptionLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        okJButton.setText("OK");
        okJButton.setEnabled(false);
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        okJButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                okJButtonKeyReleased(evt);
            }
        });

        mandatoryLabel.setFont(mandatoryLabel.getFont().deriveFont((mandatoryLabel.getFont().getStyle() | java.awt.Font.ITALIC)));
        mandatoryLabel.setText("* Mandatory fields.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(projectDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(mandatoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelJButton, okJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton)
                    .addComponent(okJButton)
                    .addComponent(mandatoryLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog.
     *
     * @param evt
     */
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**
     * Creates the new project and then closes the dialog.
     *
     * @param evt
     */
    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed


        // validate the input
        if (nameJTextField.getText().length() == 0
                || contactJTextField.getText().length() == 0
                || eMailJTextField.getText().length() == 0
                || phoneJTextField.getText().length() == 0
                || summaryJTextField.getText().length() == 0
                || descriptionJTextArea.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "All fields have to be filled in.", "Dataset Error", JOptionPane.INFORMATION_MESSAGE);
        } else {

            // check if project already exists
            if (storeBioinfoGUI.projectExists(nameJTextField.getText())) {
                JOptionPane.showMessageDialog(this, "Project named \'" + nameJTextField.getText() + "\' already exists!", "Project Error", JOptionPane.ERROR_MESSAGE);
            } else {
                this.setVisible(false);
                Project project = new Project(nameJTextField.getText(), contactJTextField.getText(), eMailJTextField.getText(),
                        phoneJTextField.getText(), summaryJTextField.getText(), descriptionJTextArea.getText());
                boolean created = storeBioinfoGUI.addProject(project);
                this.dispose();
            }
        }
    }//GEN-LAST:event_okJButtonActionPerformed

    /**
     * Creates the new project and then closes the dialog.
     *
     * @param evt
     */
    private void okJButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okJButtonKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            okJButtonActionPerformed(null);
        }
    }//GEN-LAST:event_okJButtonKeyReleased

    /**
     * Validate the input.
     * 
     * @param evt 
     */
    private void nameJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameJTextFieldKeyReleased
        validateInput();
    }//GEN-LAST:event_nameJTextFieldKeyReleased

    /**
     * Validate the input.
     * 
     * @param evt 
     */
    private void contactJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactJTextFieldKeyReleased
        validateInput();
    }//GEN-LAST:event_contactJTextFieldKeyReleased

    /**
     * Validate the input.
     * 
     * @param evt 
     */
    private void eMailJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eMailJTextFieldKeyReleased
        validateInput();
    }//GEN-LAST:event_eMailJTextFieldKeyReleased

    /**
     * Validate the input.
     * 
     * @param evt 
     */
    private void phoneJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneJTextFieldKeyReleased
        validateInput();
    }//GEN-LAST:event_phoneJTextFieldKeyReleased

    /**
     * Validate the input.
     * 
     * @param evt 
     */
    private void summaryJTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_summaryJTextFieldKeyReleased
        validateInput();
    }//GEN-LAST:event_summaryJTextFieldKeyReleased

    /**
     * Validate the input.
     * 
     * @param evt 
     */
    private void descriptionJTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionJTextAreaKeyReleased
        validateInput();
    }//GEN-LAST:event_descriptionJTextAreaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JTextField contactJTextField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JScrollPane descriptionJScrollPane;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField eMailJTextField;
    private javax.swing.JLabel eMailLabel;
    private javax.swing.JLabel mandatoryLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okJButton;
    private javax.swing.JTextField phoneJTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel projectDetailsPanel;
    private javax.swing.JTextField summaryJTextField;
    private javax.swing.JLabel summaryLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Enable/disable the OK button.
     */
    private void validateInput() {
        if (nameJTextField.getText().length() > 0 
                && contactJTextField.getText().length() > 0
                && eMailJTextField.getText().length() > 0
                && phoneJTextField.getText().length() > 0
                && summaryJTextField.getText().length() > 0
                && descriptionJTextArea.getText().length() > 0) {
            okJButton.setEnabled(true);
        } else {
            okJButton.setEnabled(false);
        }
    }
}
