package no.uib.storbioinfogui;

import java.awt.event.KeyEvent;
import no.uib.storbioinfogui.data.Project;
import javax.swing.JOptionPane;

/**
 * A dialog for creating a new Project.
 *
 * @author Harald Barsnes
 */
public class NewProjectDialog extends javax.swing.JDialog {

    private StoreBioinfoGUI storeBioinfoGUI;

    /**
     * Creates a new NewProjectDialog.
     *
     * @param storeBioinfoGUI
     * @param modal
     */
    public NewProjectDialog(StoreBioinfoGUI storeBioinfoGUI, boolean modal) {
        super(storeBioinfoGUI, modal);
        initComponents();

        this.storeBioinfoGUI = storeBioinfoGUI;

        setLocationRelativeTo(storeBioinfoGUI);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        contactJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eMailJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        summaryJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        cancelJButton = new javax.swing.JButton();
        okJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Project");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Project Details"));

        descriptionJTextArea.setColumns(5);
        descriptionJTextArea.setLineWrap(true);
        descriptionJTextArea.setRows(3);
        descriptionJTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(descriptionJTextArea);

        jLabel1.setText("Contact:");

        contactJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contactJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));

        jLabel2.setText("E-mail:");

        eMailJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        eMailJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));

        jLabel3.setText("Phone:");

        phoneJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));

        jLabel4.setText("Summary:");

        summaryJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        summaryJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));

        jLabel5.setText("Description:");

        jLabel6.setText("Name:");

        nameJTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameJTextField.setMargin(new java.awt.Insets(2, 4, 2, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameJTextField)
                            .addComponent(eMailJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(summaryJTextField)
                            .addComponent(contactJTextField))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eMailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(summaryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        okJButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                okJButtonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelJButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelJButton, okJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton)
                    .addComponent(okJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog.
     *
     * @param evt
     */
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**
     * Creates the new project and then closes the dialog.
     *
     * @param evt
     */
    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed


        // validate the input
        if (nameJTextField.getText().length() == 0
                || contactJTextField.getText().length() == 0
                || eMailJTextField.getText().length() == 0
                || phoneJTextField.getText().length() == 0
                || summaryJTextField.getText().length() == 0
                || descriptionJTextArea.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "All fields have to be filled in.", "Dataset Error", JOptionPane.INFORMATION_MESSAGE);
        } else {

            // check if project already exists
            if (storeBioinfoGUI.projectExists(nameJTextField.getText())) {
                JOptionPane.showMessageDialog(this, "Project named \'" + nameJTextField.getText() + "\' already exists!", "Project Error", JOptionPane.ERROR_MESSAGE);
            } else {
                this.setVisible(false);
                Project project = new Project(nameJTextField.getText(), contactJTextField.getText(), eMailJTextField.getText(),
                        phoneJTextField.getText(), summaryJTextField.getText(), descriptionJTextArea.getText());
                boolean created = storeBioinfoGUI.addProject(project);
                this.dispose();
            }
        }
    }//GEN-LAST:event_okJButtonActionPerformed

    /**
     * Creates the new project and then closes the dialog.
     *
     * @param evt
     */
    private void okJButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okJButtonKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            okJButtonActionPerformed(null);
        }
    }//GEN-LAST:event_okJButtonKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JTextField contactJTextField;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JTextField eMailJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton okJButton;
    private javax.swing.JTextField phoneJTextField;
    private javax.swing.JTextField summaryJTextField;
    // End of variables declaration//GEN-END:variables
}
